<a href="https://colab.research.google.com/github/arunmishrarut/Credit-card-fraud/blob/main/rough_work_arround_GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: i want to know which cuda version is being used by googlel colab

!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0


In [ ]:
#go to "Rapid release installer" and select the needed installer for Rapid.
!pip install --extra-index-url=https://pypi.nvidia.com   "cuml-cu12==25.4.*"

Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 101.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 241.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 726.0/726.0 kB 216.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.9/135.9 kB 155.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.7/50.7 kB 68.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 424.6/424.6 MB 71.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 855.3/855.3 kB 216.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 288.3/288.3 MB 98.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 195.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 565.0/565.0 MB 74.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.7/27.7 MB 163.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [ ]:
# prompt: fit  a random forest from cuml library on a dataset called "data1" having y label as "Class" and drop predictor "Time" from x

import cuml
from cuml.ensemble import RandomForestClassifier as cuRF
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Assuming 'data1' is a pandas DataFrame
# If data1 is not already loaded, you would load it here, e.g.:
data1 = pd.read_csv('data1.csv')

# Define features (X) and target (y)
y = data1['Class']
X = data1.drop(['Class'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the cuML Random Forest model
# You might need to adjust n_estimators and other parameters
cu_rf = cuRF(n_estimators=100, random_state=42)
cu_rf.fit(X_train, y_train)

# Make predictions
y_pred = cu_rf.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.11/dist-packages/cuml/internals/api_decorators.py:368: UserWarning: For reproducible results in Random Forest Classifier or for almost reproducible results in Random Forest Regressor, n_streams=1 is recommended. If n_streams is > 1, results may vary due to stream/thread timing differences, even when random_state is set
  return init_func(self, *args, **kwargs)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.97      0.77      0.86        98

    accuracy                           1.00     56962
   macro avg       0.99      0.88      0.93     56962
weighted avg       1.00      1.00      1.00     56962

[[56862     2]
 [   23    75]]


In [ ]:
# prompt: fit  a random forest from cuml library on a dataset called "data1" having y label as "Class" and drop predictor "Time" from x

import cuml
from cuml.ensemble import RandomForestClassifier as cuRF
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Assuming 'data1' is a pandas DataFrame
# If data1 is not already loaded, you would load it here, e.g.:
data1 = pd.read_csv('data1.csv')

# Define features (X) and target (y)
y = data1['Class']
X = data1.drop(['Class', 'Time'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the cuML Random Forest model
# You might need to adjust n_estimators and other parameters
cu_rf = cuRF(n_estimators=200,
    max_depth=20,
    random_state=42,
    verbose=1)
cu_rf.fit(X_train, y_train)

# Make predictions
y_pred = cu_rf.predict(X_test)

# Evaluate the model
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

/usr/local/lib/python3.11/dist-packages/cuml/internals/api_decorators.py:317: UserWarning: For reproducible results in Random Forest Classifier or for almost reproducible results in Random Forest Regressor, n_streams=1 is recommended. If n_streams is > 1, results may vary due to stream/thread timing differences, even when random_state is set
  return init_func(self, *args, **kwargs)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.99      0.76      0.86        98

    accuracy                           1.00     56962
   macro avg       0.99      0.88      0.93     56962
weighted avg       1.00      1.00      1.00     56962

[[56863     1]
 [   24    74]]


In [ ]:
# prompt: fit  a random forest from cuml library on a dataset called "data1" having y label as "Class" and drop predictor "Time" from x

import cuml
from cuml.ensemble import RandomForestClassifier as cuRF
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Assuming 'data1' is a pandas DataFrame
# If data1 is not already loaded, you would load it here, e.g.:
data1 = pd.read_csv('data1.csv')

# Define features (X) and target (y)
y = data1['Class']
X = data1.drop(['Class'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify = y)

# Initialize and train the cuML Random Forest model
# You might need to adjust n_estimators and other parameters
cu_rf = cuRF(n_estimators=100, random_state=42)
cu_rf.fit(X_train, y_train)




/usr/local/lib/python3.11/dist-packages/cuml/internals/api_decorators.py:368: UserWarning: For reproducible results in Random Forest Classifier or for almost reproducible results in Random Forest Regressor, n_streams=1 is recommended. If n_streams is > 1, results may vary due to stream/thread timing differences, even when random_state is set
  return init_func(self, *args, **kwargs)


RandomForestClassifier()

In [ ]:
# Get probabilities for minority class
y_probs = cu_rf.predict_proba(X_test).iloc[:,1]

t = 0.00
for i in range(10):
  print(f"Iteration {i+1}:")
  t = 0.05 + t
  print(f't= {t}' )
  # Set custom threshold (e.g., 0.3 instead of 0.5)
  adjusted_preds = (y_probs >= t).astype(int)
  print(classification_report(y_test, adjusted_preds))

Iteration 1:
t= 0.05
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.44      0.89      0.59        98

    accuracy                           1.00     56962
   macro avg       0.72      0.94      0.79     56962
weighted avg       1.00      1.00      1.00     56962

Iteration 2:
t= 0.1
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.69      0.89      0.78        98

    accuracy                           1.00     56962
   macro avg       0.85      0.94      0.89     56962
weighted avg       1.00      1.00      1.00     56962

Iteration 3:
t= 0.15000000000000002
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.80      0.88      0.84        98

    accuracy                           1.00     56962
   macro avg       0.90      0.94      0.92     569

/usr/local/lib/python3.11/dist-packages/cuml/internals/api_decorators.py:368: UserWarning: For reproducible results in Random Forest Classifier or for almost reproducible results in Random Forest Regressor, n_streams=1 is recommended. If n_streams is > 1, results may vary due to stream/thread timing differences, even when random_state is set
  return init_func(self, *args, **kwargs)


Accuracy: 0.9982619992275552

Confusion Matrix:
 [[56774    90]
 [    9    89]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.50      0.91      0.64        98

    accuracy                           1.00     56962
   macro avg       0.75      0.95      0.82     56962
weighted avg       1.00      1.00      1.00     56962



In [ ]:
#SMOTE with randomforest threshold = 0.25
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from imblearn.over_sampling import SMOTE

# Only this import is changed for cuML
from cuml.ensemble import RandomForestClassifier as cuRF
import numpy as np

data1 = pd.read_csv('data1.csv')

# Assume data1 is your DataFrame and 'Class' is the label column
X = data1.drop('Class', axis=1)
y = data1['Class']


# Split before SMOTE to avoid data leakage (recommended practice)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=43, stratify=y)

# Apply SMOTE to the training data only
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# Train a classifier (cuML Random Forest on GPU)
clf = cuRF(random_state=42)
clf.fit(X_train_res.values, y_train_res.values)  # cuML expects numpy arrays

# Predict probabilities on the test set
y_proba = clf.predict_proba(X_test.values)  # shape: (n_samples, n_classes)

# Use threshold = 0.25 for positive class (assuming binary classification and positive class is 1)
threshold = 0.25
y_pred = (y_proba[:, 1] >= threshold).astype(int)

# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


/usr/local/lib/python3.11/dist-packages/cuml/internals/api_decorators.py:368: UserWarning: For reproducible results in Random Forest Classifier or for almost reproducible results in Random Forest Regressor, n_streams=1 is recommended. If n_streams is > 1, results may vary due to stream/thread timing differences, even when random_state is set
  return init_func(self, *args, **kwargs)


Accuracy: 0.9982619992275552

Confusion Matrix:
 [[56774    90]
 [    9    89]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     56864
           1       0.50      0.91      0.64        98

    accuracy                           1.00     56962
   macro avg       0.75      0.95      0.82     56962
weighted avg       1.00      1.00      1.00     56962

